### ISSUE TITLE
int64 or uint64

### ISSUE THREAD

**Issue by artem1996** [viciious/go-tarantool#19]
When returning a numeric value (number) from the tarantool, sometimes it returns int64, sometimes uint64. It depends on the value of the number. 0 is recognized as int64, 126 as uint64.
Why can not you always use the same type?
For example:
1) the return of the number of records
2) tuple with a number value

**Comment by viciious** [comment]
go-tarantool uses tinylib/msgpack to decode the returned tuple data. The msgpack spec doesn't define variable integer types for individual languages so it's all very much implementation dependent. Most of the libraries we've encountered use the signed type for 0.

**Comment by viciious** [comment]
I've since created a small utility package to safely convert msgpack-encoded numbers from interfaces to integer types.
