### ISSUE TITLE
Use go modules

### ISSUE THREAD

**Issue by ernado** [viciious/go-tarantool#37]
See [Migrating to go modules](https://blog.golang.org/migrating-to-go-modules) article.

- [ ] Add go.mod file via `go mod init`
- [ ] Remove dep files (`rm -rf Gopkg.* vendor`)
- [ ] Start using semantic versioning via git tags

The **go1.13** is out, **$GOPATH** is [going to be deprecated](https://github.com/golang/go/issues/30329#issuecomment-465690186), [dep](https://github.com/golang/dep) is not actively maintained and is effectively deprecated by go modules.

**Comment by viciious** [comment]
Done
